Add tabs to profile (+ convert settings form submissions to AJAX)
big-band-roulette/musicians-portal pull request #46
Opened 2023-10-01 16:09 UTC by THargreaves

Add tabs to the profile page as per #36. In doing this, all form submissions must be switch to AJAX to avoid the tabset reseting to the first pane after each form submission (and corresponding redirect). This solves #24 in the process.

2023-10-01 16:10 UTC, THargreaves commented
Just need to add AJAX requests for the instruments panel and then good to merge.

2023-10-01 16:51 UTC, carlashworth commented on templates/profile/themes.html
> +</form>
add empty line?

2023-10-01 16:52 UTC, carlashworth commented on templates/profile/instruments.html
> +{% endif %}
extra empty line?

2023-10-01 16:52 UTC, carlashworth commented on templates/profile/notifications.html
> +</script>
"

2023-10-01 16:52 UTC, carlashworth commented on templates/profile.html
> +{% endif %}
line at end?

2023-10-01 16:53 UTC, carlashworth commented on templates/profile/themes.html
> +  suggestion, you will be more likely to be selected for the band</p>
potentially same line

2023-10-01 16:54 UTC, carlashworth requested changes
Perfect functionally, what a banger of a PR. Just (I might be wrong) a few spacing changes, but then just merge that, really nice changes.

2023-10-02 10:22 UTC, THargreaves commented on templates/profile/themes.html
> +  suggestion, you will be more likely to be selected for the band</p>
Personally, I'm a fan of following a sensible recommended line length (~120 max):
https://stackoverflow.com/questions/2886603/is-there-a-recommended-maximum-line-length-for-html-or-javascript

2023-10-02 11:39 UTC, merged